<?php

namespace App\Filament\Resources\TestResource\RelationManagers;

use App\Models\TestAssignment;
use Filament\Forms\Form;
use Filament\Resources\RelationManagers\RelationManager;
use Filament\Tables;
use Filament\Tables\Actions\Action;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

/**
 * مدير علاقة تعيينات الاختبار (Test Assignments) داخل Filament.
 *
 * Arabic: يعرض تعيينات الطلاب لاختبار معيّن، مع إجراءات سريعة لتحديث الحالة (غياب مبرر/غير مبرر)،
 * ويقيّد الاستعلام حسب الصلاحيات عبر `TestAssignmentPolicy`.
 * EN: Manages assignments relation for a test with quick status actions and policy-based scoping.
 */
class AssignmentsRelationManager extends RelationManager
{
    protected static string $relationship = 'assignments';

    protected static ?string $title = 'التعيينات';

    /**
     * نموذج تعديل/إنشاء تعيين.
     *
     * Arabic: حالياً لا يحتوي حقول لأن التعيينات غالباً تُولّد تلقائياً بواسطة الخدمات (Sampling/service).
     * EN: Empty schema by design; assignments are typically generated automatically.
     */
    public function form(Form $form): Form
    {
        return $form->schema([
            // assignments generated by sampling/service; editing manually is optional
        ]);
    }

    /**
     * جدول عرض تعيينات الاختبار.
     *
     * Arabic: يعرض الطالب/الحلقة/المركز/الحالة وتاريخ التعيين ووجود نتيجة، مع إجراءات تغيّر حالة التعيين.
     * EN: Assignments table with quick actions to set absence status.
     */
    public function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('student.full_name')->label('الطالب')->searchable(),
                Tables\Columns\TextColumn::make('halaqah.name')->label('الحلقة')->sortable(),
                Tables\Columns\TextColumn::make('halaqah.center.name')->label('المركز')->sortable(),
                Tables\Columns\TextColumn::make('status')->label('الحالة')->badge(),
                Tables\Columns\TextColumn::make('assigned_at')->label('تاريخ التعيين')->dateTime('Y/m/d H:i')->sortable(),
                Tables\Columns\IconColumn::make('result.id')->label('تمت النتيجة')->boolean(),
            ])
            ->actions([
                Action::make('absent_excused')
                    ->label('غياب مبرر')
                    ->requiresConfirmation()
                    ->action(fn (TestAssignment $record) => $record->update(['status' => TestAssignment::STATUS_ABSENT_EXCUSED])),
                Action::make('absent_unexcused')
                    ->label('غياب غير مبرر')
                    ->requiresConfirmation()
                    ->action(fn (TestAssignment $record) => $record->update(['status' => TestAssignment::STATUS_ABSENT_UNEXCUSED])),
            ])
            ->modifyQueryUsing(function (Builder $query) {
                /** @var \App\Models\User|null $user */
                $user = auth()->user();
                if (! $user) {
                    return $query->whereRaw('1=0');
                }
                $policy = app(\App\Policies\TestAssignmentPolicy::class);
                return $policy->scopeQueryForUser($user, $query)->with(['student', 'halaqah.center', 'result']);
            });
    }
}

